const INIT_WEATHER_DATA = 'INIT_WEATHER_DATA';
const SET_WETHEAR_DATA_DAY = 'SET_WETHEAR_DATA_DAY';
const SET_WETHEAR_DATA_WEEK = 'SET_WETHEAR_DATA_WEEK';
const SET_CITY_NAME = 'SET_CITY_NAME'; 

export {
    INIT_WEATHER_DATA,
    SET_WETHEAR_DATA_DAY,
    SET_WETHEAR_DATA_WEEK,
    SET_CITY_NAME
}