const INIT_WEATHER_DATA = 'INIT_WEATHER_DATA';
const SET_WETHEAR_DATA_DAY = 'SET_WETHEAR_DATA_DAY';
const SET_WETHEAR_DATA_WEEK = 'SET_WETHEAR_DATA_WEEK';

export {
    INIT_WEATHER_DATA,
    SET_WETHEAR_DATA_DAY,
    SET_WETHEAR_DATA_WEEK
}